### ISSUE TITLE
How can add help text?

### ISSUE THREAD

**Issue by PoojaJadav** [emilianotisato/nova-tinymce#47]
I want to add help with my field like this : 

```
NovaTinyMCE::make(__('Description'), 'description')
                    ->rules('required')
                    ->options([
                        'height' => '500',
                    ])
                ->help('Here is my help'),
```

Can you give me suggestions that how can I add help text?

**Comment by JonathanDoelan** [comment]
Maybe [this](https://github.com/laravel/nova-issues/issues/3095#issuecomment-737142016) helps?

**Comment by crynobone** [comment]
This package need to implements `helpText` under `components/FormField.vue`. Not Laravel Nova issue.

**Comment by Jon78** [comment]
This was fixed in https://github.com/emilianotisato/nova-tinymce/pull/46. PR has been merged but the version number has not changed. In your composer.json you could refer to `"emilianotisato/nova-tinymce": "master",`, this way you will get the latest commits

**Comment by JonathanDoelan** [comment]
@Jon78 I added `"emilianotisato/nova-tinymce": "master",` but then tinymce does not show icons anymore …
<img width="965" alt="bug" src="https://user-images.githubusercontent.com/2291224/104172895-44c0fc80-5405-11eb-8353-e964fb9eabe8.png">
… and help text is still not appearing! :(

So … @emilianotisato can you please [update the project for composer](https://github.com/emilianotisato/nova-tinymce/pull/46#issuecomment-744403705)?

**Comment by emilianotisato** [comment]
Sorry the delay guys. This is now merged and added to latest tag 1.2
